sudo: 'required'

services:
  - 'docker'

before_install:
  - gem install bundler --pre
  - gem install bundler --version '1.7.4'
  - './.travis/main.sh'
  - 'make network'
  - 'make volume'

script:
  - 'make image'
  - 'make run'  
  - 'make test'
after_success:
  - 'make clean'
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make push-image ;
    fi

notifications:
  email: false
